-- AlterTable
ALTER TABLE "posts" ADD COLUMN     "confidence" TEXT,
ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "sourceName" TEXT,
ADD COLUMN     "sourceUrl" TEXT,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'PUBLISHED';
