import {
  IsString,
  IsBoolean,
  IsEnum,
  IsOptional,
  IsInt,
  IsEmail,
  IsDateString,
  IsArray,
  ArrayMaxSize,
  Min,
  Max,
  MinLength,
  MaxLength,
  ValidateIf,
  ValidateNested,
  Matches,
  IsNumber,
  IsIn,
} from 'class-validator';
import { Type } from 'class-transformer';
import { Transform } from 'class-transformer';
import {
  PostCategory,
  JobSubCategory,
  Region,
  SalaryType,
  EmploymentType,
  TherapyTag,
} from '@prisma/client';
import {
  sanitizeTitle,
  sanitizeContent,
} from '../../common/utils/sanitize.util';

export class CreatePostDto {
  @IsString()
  @MinLength(1)
  @MaxLength(200)
  @Transform(sanitizeTitle)
  title: string;

  @IsString()
  @MinLength(1)
  @MaxLength(10000)
  @Transform(sanitizeContent)
  content: string;

  @IsEnum(PostCategory)
  @IsOptional()
  category?: PostCategory;

  @IsBoolean()
  @IsOptional()
  isAnonymous?: boolean;

  // === 구인공고 전용 필드 (기존) ===
  @IsEnum(JobSubCategory)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  jobSubCategory?: JobSubCategory;

  @IsEnum(Region)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  region?: Region;

  @IsEnum(SalaryType)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  salaryType?: SalaryType;

  @IsInt()
  @Min(0)
  @IsOptional()
  @ValidateIf(
    (o) =>
      o.category === PostCategory.JOB_POSTING &&
      o.salaryType !== SalaryType.NEGOTIABLE,
  )
  salaryMin?: number;

  @IsInt()
  @Min(0)
  @IsOptional()
  @ValidateIf(
    (o) =>
      o.category === PostCategory.JOB_POSTING &&
      o.salaryType !== SalaryType.NEGOTIABLE,
  )
  salaryMax?: number;

  // === 1순위: 핵심 채용 정보 ===
  @IsString()
  @MaxLength(100)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  @Transform(sanitizeTitle)
  organizationName?: string;

  @IsString()
  @MaxLength(20)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  contactPhone?: string;

  @IsEmail()
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  contactEmail?: string;

  @IsString()
  @MaxLength(50)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  @Transform(sanitizeTitle)
  contactKakao?: string;

  @IsDateString()
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  deadline?: string;

  @IsBoolean()
  @IsOptional()
  isAutoClose?: boolean;

  @IsInt()
  @Min(1)
  @Max(1000)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  recruitCount?: number;

  @IsString()
  @MaxLength(50)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  @Transform(sanitizeTitle)
  workingHours?: string;

  // === 2순위: 상세 정보 ===
  @IsEnum(EmploymentType)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  employmentType?: EmploymentType;

  @IsString()
  @MaxLength(2000)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  @Transform(sanitizeTitle)
  benefits?: string;

  @IsString()
  @MaxLength(2000)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  @Transform(sanitizeTitle)
  requirements?: string;

  @IsString()
  @MaxLength(200)
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  @Transform(sanitizeTitle)
  detailAddress?: string;

  // === 치료/교육 분야 태그 (다중 선택) ===
  @IsArray()
  @IsEnum(TherapyTag, { each: true })
  @ArrayMaxSize(8, { message: '태그는 최대 8개까지 선택 가능합니다' })
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.JOB_POSTING)
  therapyTags?: TherapyTag[];

  // === 자동생성 콘텐츠 필드 (봇 전용, 일반 사용자 입력은 서비스에서 무시) ===
  @IsOptional()
  @IsIn(['PUBLISHED', 'DRAFT'])
  status?: string = 'PUBLISHED';

  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean = false;

  @IsOptional()
  @IsString()
  sourceUrl?: string;

  @IsOptional()
  @IsString()
  sourceName?: string;

  @IsOptional()
  @IsString()
  confidence?: string;

  // === 첨부파일 (수업자료 전용) ===
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => AttachmentInputDto)
  @ArrayMaxSize(5, { message: '첨부파일은 최대 5개까지 가능합니다' })
  @IsOptional()
  @ValidateIf((o) => o.category === PostCategory.CLASS_MATERIAL)
  attachments?: AttachmentInputDto[];
}

// 첨부파일 입력 DTO (유효성 검증 포함)
export class AttachmentInputDto {
  @IsString()
  @Matches(
    /^\/uploads\/material\/[a-zA-Z0-9_-]+\.(pdf|doc|docx|ppt|pptx|xls|xlsx|hwp)$/i,
    {
      message: '유효하지 않은 파일 경로입니다',
    },
  )
  fileUrl: string;

  @IsString()
  @MaxLength(255)
  fileName: string;

  @IsNumber()
  @Min(1)
  @Max(20 * 1024 * 1024) // 20MB
  fileSize: number;

  @IsString()
  @Matches(
    /^(application\/(pdf|msword|vnd\.openxmlformats-officedocument\.(wordprocessingml\.document|presentationml\.presentation|spreadsheetml\.sheet)|vnd\.ms-(powerpoint|excel)|x-hwp|haansofthwp))$/,
    { message: '유효하지 않은 파일 형식입니다' },
  )
  mimeType: string;
}

// 하위 호환성을 위한 타입 별칭
export type AttachmentInput = AttachmentInputDto;
